name: Build APT Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dpkg-scanpackages
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev fakeroot

      - name: Make scripts executable
        run: chmod +x tools/apt/build-repo.sh || true

      - name: Build .deb and repo
        run: bash tools/apt/build-repo.sh

      - name: Upload repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: tns-apt-repo
          path: webclip/repo

      - name: Deploy repo to gh-pages (webclip/repo)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: webclip/repo
          destination_dir: webclip/repo

